//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EServicesWithAngular.Domain.Common;

namespace ERP_OvertimeServices
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.dirac.com/", ConfigurationName = "OvertimeRequestService")]
    public interface OvertimeRequestService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<deleteOvertimeRequestResponse> deleteOvertimeRequestAsync(deleteOvertimeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<IsValidBudgetResponse> IsValidBudgetAsync(IsValidBudget request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<getEmpReleasedOvertimeRequestListResponse> getEmpReleasedOvertimeRequestListAsync(getEmpReleasedOvertimeRequestList request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<findoneResponse> findoneAsync(findone request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<saveNewResponse> saveNewAsync(saveNew request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<deleteovertimerequestResponse1> deleteovertimerequest1Async(deleteovertimerequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<releaseOvertimeRequestResponse> releaseOvertimeRequestAsync(releaseOvertimeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<verifyBeforeSaveResponse> verifyBeforeSaveAsync(verifyBeforeSave request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<getEmpOvertimeRequestListResponse> getEmpOvertimeRequestListAsync(getEmpOvertimeRequestList request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<getAuthorizationPersonResponse> getAuthorizationPersonAsync(getAuthorizationPerson request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<updateExistingOvertimeRequestResponse> updateExistingOvertimeRequestAsync(updateExistingOvertimeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<updateKtaJobIdResponse> updateKtaJobIdAsync(updateKtaJobId request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<cancelOvertimeRequestResponse> cancelOvertimeRequestAsync(cancelOvertimeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<findByJobIdResponse> findByJobIdAsync(findByJobId request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.dirac.com/")]
    public partial class dsOvertimeRequestResult
    {

        private bool successField;

        private string errorMsgCodeField;

        private string errorMsgDescriptionField;

        private string errorMsgDescriptionarField;

        private overtimeRequest overtimeRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string errorMsgCode
        {
            get
            {
                return this.errorMsgCodeField;
            }
            set
            {
                this.errorMsgCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string errorMsgDescription
        {
            get
            {
                return this.errorMsgDescriptionField;
            }
            set
            {
                this.errorMsgDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string errorMsgDescriptionar
        {
            get
            {
                return this.errorMsgDescriptionarField;
            }
            set
            {
                this.errorMsgDescriptionarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public overtimeRequest overtimeRequest
        {
            get
            {
                return this.overtimeRequestField;
            }
            set
            {
                this.overtimeRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.dirac.com/")]
    public partial class overtimeRequest
    {

        private long hR_OVERTIMEREQUEST_IDField;

        private string dateTrxField;

        private string documentNoField;

        private string docStatusField;

        private string docActionField;

        private long docTypeIDField;

        private long employeeIDField;

        private lookup employeeField;

        private long daysField;

        private string dateFromField;

        private string dateToField;

        private long durationField;

        private long durationweekendField;

        private string isDmApprovalField;

        private string isDsApprovalField;

        private string isAdminApprovalField;

        private string isOtherApprovalField;

        private long hoursField;

        private long weekendhoursField;

        private string onSundayField;

        private string onMondayField;

        private string onTuesdayField;

        private string onWednesdayField;

        private string onThursdayField;

        private string onFridayField;

        private string onSaturdayField;

        private overtimeRequestLine[] linesField;

        private lookup actionField;

        private lookup statusField;

        private lookup doctypeField;

        private decimal overtimeValueField;

        private string kTAJobIDField;

        private int actualOvertimeDaysField;

        private int chosenDaysCountField;

        private bool chosenDaysCountFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long HR_OVERTIMEREQUEST_ID
        {
            get
            {
                return this.hR_OVERTIMEREQUEST_IDField;
            }
            set
            {
                this.hR_OVERTIMEREQUEST_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string dateTrx
        {
            get
            {
                return this.dateTrxField;
            }
            set
            {
                this.dateTrxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string documentNo
        {
            get
            {
                return this.documentNoField;
            }
            set
            {
                this.documentNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string docStatus
        {
            get
            {
                return this.docStatusField;
            }
            set
            {
                this.docStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string docAction
        {
            get
            {
                return this.docActionField;
            }
            set
            {
                this.docActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public long docTypeID
        {
            get
            {
                return this.docTypeIDField;
            }
            set
            {
                this.docTypeIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public long employeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public lookup employee
        {
            get
            {
                return this.employeeField;
            }
            set
            {
                this.employeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public long days
        {
            get
            {
                return this.daysField;
            }
            set
            {
                this.daysField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string dateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string dateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public long duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public long durationweekend
        {
            get
            {
                return this.durationweekendField;
            }
            set
            {
                this.durationweekendField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string isDmApproval
        {
            get
            {
                return this.isDmApprovalField;
            }
            set
            {
                this.isDmApprovalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string isDsApproval
        {
            get
            {
                return this.isDsApprovalField;
            }
            set
            {
                this.isDsApprovalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string isAdminApproval
        {
            get
            {
                return this.isAdminApprovalField;
            }
            set
            {
                this.isAdminApprovalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string isOtherApproval
        {
            get
            {
                return this.isOtherApprovalField;
            }
            set
            {
                this.isOtherApprovalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public long hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public long weekendhours
        {
            get
            {
                return this.weekendhoursField;
            }
            set
            {
                this.weekendhoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string onSunday
        {
            get
            {
                return this.onSundayField;
            }
            set
            {
                this.onSundayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public string onMonday
        {
            get
            {
                return this.onMondayField;
            }
            set
            {
                this.onMondayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string onTuesday
        {
            get
            {
                return this.onTuesdayField;
            }
            set
            {
                this.onTuesdayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string onWednesday
        {
            get
            {
                return this.onWednesdayField;
            }
            set
            {
                this.onWednesdayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public string onThursday
        {
            get
            {
                return this.onThursdayField;
            }
            set
            {
                this.onThursdayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string onFriday
        {
            get
            {
                return this.onFridayField;
            }
            set
            {
                this.onFridayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string onSaturday
        {
            get
            {
                return this.onSaturdayField;
            }
            set
            {
                this.onSaturdayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lines", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public overtimeRequestLine[] Lines
        {
            get
            {
                return this.linesField;
            }
            set
            {
                this.linesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
        public lookup action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public lookup status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 29)]
        public lookup doctype
        {
            get
            {
                return this.doctypeField;
            }
            set
            {
                this.doctypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
        public decimal overtimeValue
        {
            get
            {
                return this.overtimeValueField;
            }
            set
            {
                this.overtimeValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
        public string KTAJobID
        {
            get
            {
                return this.kTAJobIDField;
            }
            set
            {
                this.kTAJobIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
        public int actualOvertimeDays
        {
            get
            {
                return this.actualOvertimeDaysField;
            }
            set
            {
                this.actualOvertimeDaysField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public int chosenDaysCount
        {
            get
            {
                return this.chosenDaysCountField;
            }
            set
            {
                this.chosenDaysCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chosenDaysCountSpecified
        {
            get
            {
                return this.chosenDaysCountFieldSpecified;
            }
            set
            {
                this.chosenDaysCountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.dirac.com/")]
    public partial class lookup
    {

        private long idField;

        private bool idFieldSpecified;

        private string codeField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.dirac.com/")]
    public partial class overtimeRequestLine
    {

        private long hR_OVERTIMEREQUESTLINE_IDField;

        private string dateTrxField;

        private int hoursField;

        private int hR_OVERTIMEREQUEST_IDField;

        private string dayNameEnField;

        private string dayNameArField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long HR_OVERTIMEREQUESTLINE_ID
        {
            get
            {
                return this.hR_OVERTIMEREQUESTLINE_IDField;
            }
            set
            {
                this.hR_OVERTIMEREQUESTLINE_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string dateTrx
        {
            get
            {
                return this.dateTrxField;
            }
            set
            {
                this.dateTrxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int HR_OVERTIMEREQUEST_ID
        {
            get
            {
                return this.hR_OVERTIMEREQUEST_IDField;
            }
            set
            {
                this.hR_OVERTIMEREQUEST_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string DayNameEn
        {
            get
            {
                return this.dayNameEnField;
            }
            set
            {
                this.dayNameEnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string DayNameAr
        {
            get
            {
                return this.dayNameArField;
            }
            set
            {
                this.dayNameArField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteOvertimeRequest", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class deleteOvertimeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public deleteOvertimeRequest()
        {
        }

        public deleteOvertimeRequest(long overtimeRequestID)
        {
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteOvertimeRequestResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class deleteOvertimeRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult overtimeRequest;

        public deleteOvertimeRequestResponse()
        {
        }

        public deleteOvertimeRequestResponse(dsOvertimeRequestResult overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "IsValidBudget", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class IsValidBudget
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long empID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public IsValidBudget()
        {
        }

        public IsValidBudget(long empID, long overtimeRequestID)
        {
            this.empID = empID;
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "IsValidBudgetResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class IsValidBudgetResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result;

        public IsValidBudgetResponse()
        {
        }

        public IsValidBudgetResponse(int result)
        {
            this.result = result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getEmpReleasedOvertimeRequestList", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getEmpReleasedOvertimeRequestList
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long employeeid;

        public getEmpReleasedOvertimeRequestList()
        {
        }

        public getEmpReleasedOvertimeRequestList(long employeeid)
        {
            this.employeeid = employeeid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getEmpReleasedOvertimeRequestListResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getEmpReleasedOvertimeRequestListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("overtimeRequest", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest[] overtimeRequest;

        public getEmpReleasedOvertimeRequestListResponse()
        {
        }

        public getEmpReleasedOvertimeRequestListResponse(overtimeRequest[] overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "findone", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class findone
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public findone()
        {
        }

        public findone(long overtimeRequestID)
        {
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "findoneResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class findoneResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest overtimeRequest;

        public findoneResponse()
        {
        }

        public findoneResponse(overtimeRequest overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "saveNew", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class saveNew
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest overtimeRequest;

        public saveNew()
        {
        }

        public saveNew(overtimeRequest overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "saveNewResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class saveNewResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult overtimeRequest;

        public saveNewResponse()
        {
        }

        public saveNewResponse(dsOvertimeRequestResult overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteovertimerequest", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class deleteovertimerequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public deleteovertimerequest1()
        {
        }

        public deleteovertimerequest1(long overtimeRequestID)
        {
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "deleteovertimerequestResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class deleteovertimerequestResponse1
    {

        public deleteovertimerequestResponse1()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "releaseOvertimeRequest", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class releaseOvertimeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public releaseOvertimeRequest()
        {
        }

        public releaseOvertimeRequest(long overtimeRequestID)
        {
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "releaseOvertimeRequestResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class releaseOvertimeRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult overtimeRequest;

        public releaseOvertimeRequestResponse()
        {
        }

        public releaseOvertimeRequestResponse(dsOvertimeRequestResult overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "verifyBeforeSave", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class verifyBeforeSave
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest overtimeRequest;

        public verifyBeforeSave()
        {
        }

        public verifyBeforeSave(overtimeRequest overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "verifyBeforeSaveResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class verifyBeforeSaveResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult result;

        public verifyBeforeSaveResponse()
        {
        }

        public verifyBeforeSaveResponse(dsOvertimeRequestResult result)
        {
            this.result = result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getEmpOvertimeRequestList", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getEmpOvertimeRequestList
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long empID;

        public getEmpOvertimeRequestList()
        {
        }

        public getEmpOvertimeRequestList(long empID)
        {
            this.empID = empID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getEmpOvertimeRequestListResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getEmpOvertimeRequestListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("overtimeRequest", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest[] overtimeRequest;

        public getEmpOvertimeRequestListResponse()
        {
        }

        public getEmpOvertimeRequestListResponse(overtimeRequest[] overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getAuthorizationPerson", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getAuthorizationPerson
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long employeeid;

        public getAuthorizationPerson()
        {
        }

        public getAuthorizationPerson(long employeeid)
        {
            this.employeeid = employeeid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getAuthorizationPersonResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class getAuthorizationPersonResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;

        public getAuthorizationPersonResponse()
        {
        }

        public getAuthorizationPersonResponse(string result)
        {
            this.result = result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateExistingOvertimeRequest", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class updateExistingOvertimeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest overtimeRequest;

        public updateExistingOvertimeRequest()
        {
        }

        public updateExistingOvertimeRequest(overtimeRequest overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateExistingOvertimeRequestResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class updateExistingOvertimeRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult overtimeRequest;

        public updateExistingOvertimeRequestResponse()
        {
        }

        public updateExistingOvertimeRequestResponse(dsOvertimeRequestResult overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateKtaJobId", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class updateKtaJobId
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimerequestID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ktaJobID;

        public updateKtaJobId()
        {
        }

        public updateKtaJobId(long overtimerequestID, string ktaJobID)
        {
            this.overtimerequestID = overtimerequestID;
            this.ktaJobID = ktaJobID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateKtaJobIdResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class updateKtaJobIdResponse
    {

        public updateKtaJobIdResponse()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "cancelOvertimeRequest", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class cancelOvertimeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long overtimeRequestID;

        public cancelOvertimeRequest()
        {
        }

        public cancelOvertimeRequest(long overtimeRequestID)
        {
            this.overtimeRequestID = overtimeRequestID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "cancelOvertimeRequestResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class cancelOvertimeRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dsOvertimeRequestResult overtimeRequest;

        public cancelOvertimeRequestResponse()
        {
        }

        public cancelOvertimeRequestResponse(dsOvertimeRequestResult overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "findByJobId", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class findByJobId
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ktajobid;

        public findByJobId()
        {
        }

        public findByJobId(string ktajobid)
        {
            this.ktajobid = ktajobid;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "findByJobIdResponse", WrapperNamespace = "http://service.dirac.com/", IsWrapped = true)]
    public partial class findByJobIdResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.dirac.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public overtimeRequest overtimeRequest;

        public findByJobIdResponse()
        {
        }

        public findByJobIdResponse(overtimeRequest overtimeRequest)
        {
            this.overtimeRequest = overtimeRequest;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface OvertimeRequestServiceChannel : OvertimeRequestService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class OvertimeRequestServiceClient : System.ServiceModel.ClientBase<OvertimeRequestService>, OvertimeRequestService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public OvertimeRequestServiceClient() :
                base(OvertimeRequestServiceClient.GetDefaultBinding(), OvertimeRequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OvertimeRequestServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OvertimeRequestServiceClient(EndpointConfiguration endpointConfiguration) :
                base(OvertimeRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), OvertimeRequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OvertimeRequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(OvertimeRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OvertimeRequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(OvertimeRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OvertimeRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<deleteOvertimeRequestResponse> OvertimeRequestService.deleteOvertimeRequestAsync(deleteOvertimeRequest request)
        {
            return base.Channel.deleteOvertimeRequestAsync(request);
        }

        public System.Threading.Tasks.Task<deleteOvertimeRequestResponse> deleteOvertimeRequestAsync(long overtimeRequestID)
        {
            deleteOvertimeRequest inValue = new deleteOvertimeRequest();
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).deleteOvertimeRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IsValidBudgetResponse> OvertimeRequestService.IsValidBudgetAsync(IsValidBudget request)
        {
            return base.Channel.IsValidBudgetAsync(request);
        }

        public System.Threading.Tasks.Task<IsValidBudgetResponse> IsValidBudgetAsync(long empID, long overtimeRequestID)
        {
            IsValidBudget inValue = new IsValidBudget();
            inValue.empID = empID;
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).IsValidBudgetAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getEmpReleasedOvertimeRequestListResponse> OvertimeRequestService.getEmpReleasedOvertimeRequestListAsync(getEmpReleasedOvertimeRequestList request)
        {
            return base.Channel.getEmpReleasedOvertimeRequestListAsync(request);
        }

        public System.Threading.Tasks.Task<getEmpReleasedOvertimeRequestListResponse> getEmpReleasedOvertimeRequestListAsync(long employeeid)
        {
            getEmpReleasedOvertimeRequestList inValue = new getEmpReleasedOvertimeRequestList();
            inValue.employeeid = employeeid;
            return ((OvertimeRequestService)(this)).getEmpReleasedOvertimeRequestListAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<findoneResponse> OvertimeRequestService.findoneAsync(findone request)
        {
            return base.Channel.findoneAsync(request);
        }

        public System.Threading.Tasks.Task<findoneResponse> findoneAsync(long overtimeRequestID)
        {
            findone inValue = new findone();
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).findoneAsync(inValue);
        }

        public System.Threading.Tasks.Task<saveNewResponse> saveNewAsync(saveNew request)
        {
            return base.Channel.saveNewAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<deleteovertimerequestResponse1> OvertimeRequestService.deleteovertimerequest1Async(deleteovertimerequest1 request)
        {
            return base.Channel.deleteovertimerequest1Async(request);
        }

        public System.Threading.Tasks.Task<deleteovertimerequestResponse1> deleteovertimerequest1Async(long overtimeRequestID)
        {
            deleteovertimerequest1 inValue = new deleteovertimerequest1();
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).deleteovertimerequest1Async(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<releaseOvertimeRequestResponse> OvertimeRequestService.releaseOvertimeRequestAsync(releaseOvertimeRequest request)
        {
            return base.Channel.releaseOvertimeRequestAsync(request);
        }

        public System.Threading.Tasks.Task<releaseOvertimeRequestResponse> releaseOvertimeRequestAsync(long overtimeRequestID)
        {
            releaseOvertimeRequest inValue = new releaseOvertimeRequest();
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).releaseOvertimeRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<verifyBeforeSaveResponse> OvertimeRequestService.verifyBeforeSaveAsync(verifyBeforeSave request)
        {
            return base.Channel.verifyBeforeSaveAsync(request);
        }

        public System.Threading.Tasks.Task<verifyBeforeSaveResponse> verifyBeforeSaveAsync(overtimeRequest overtimeRequest)
        {
            verifyBeforeSave inValue = new verifyBeforeSave();
            inValue.overtimeRequest = overtimeRequest;
            return ((OvertimeRequestService)(this)).verifyBeforeSaveAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getEmpOvertimeRequestListResponse> OvertimeRequestService.getEmpOvertimeRequestListAsync(getEmpOvertimeRequestList request)
        {
            return base.Channel.getEmpOvertimeRequestListAsync(request);
        }

        public System.Threading.Tasks.Task<getEmpOvertimeRequestListResponse> getEmpOvertimeRequestListAsync(long empID)
        {
            getEmpOvertimeRequestList inValue = new getEmpOvertimeRequestList();
            inValue.empID = empID;
            return ((OvertimeRequestService)(this)).getEmpOvertimeRequestListAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getAuthorizationPersonResponse> OvertimeRequestService.getAuthorizationPersonAsync(getAuthorizationPerson request)
        {
            return base.Channel.getAuthorizationPersonAsync(request);
        }

        public System.Threading.Tasks.Task<getAuthorizationPersonResponse> getAuthorizationPersonAsync(long employeeid)
        {
            getAuthorizationPerson inValue = new getAuthorizationPerson();
            inValue.employeeid = employeeid;
            return ((OvertimeRequestService)(this)).getAuthorizationPersonAsync(inValue);
        }

        public System.Threading.Tasks.Task<updateExistingOvertimeRequestResponse> updateExistingOvertimeRequestAsync(updateExistingOvertimeRequest request)
        {
            return base.Channel.updateExistingOvertimeRequestAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<updateKtaJobIdResponse> OvertimeRequestService.updateKtaJobIdAsync(updateKtaJobId request)
        {
            return base.Channel.updateKtaJobIdAsync(request);
        }

        public System.Threading.Tasks.Task<updateKtaJobIdResponse> updateKtaJobIdAsync(long overtimerequestID, string ktaJobID)
        {
            updateKtaJobId inValue = new updateKtaJobId();
            inValue.overtimerequestID = overtimerequestID;
            inValue.ktaJobID = ktaJobID;
            return ((OvertimeRequestService)(this)).updateKtaJobIdAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cancelOvertimeRequestResponse> OvertimeRequestService.cancelOvertimeRequestAsync(cancelOvertimeRequest request)
        {
            return base.Channel.cancelOvertimeRequestAsync(request);
        }

        public System.Threading.Tasks.Task<cancelOvertimeRequestResponse> cancelOvertimeRequestAsync(long overtimeRequestID)
        {
            cancelOvertimeRequest inValue = new cancelOvertimeRequest();
            inValue.overtimeRequestID = overtimeRequestID;
            return ((OvertimeRequestService)(this)).cancelOvertimeRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<findByJobIdResponse> OvertimeRequestService.findByJobIdAsync(findByJobId request)
        {
            return base.Channel.findByJobIdAsync(request);
        }

        public System.Threading.Tasks.Task<findByJobIdResponse> findByJobIdAsync(string ktajobid)
        {
            findByJobId inValue = new findByJobId();
            inValue.ktajobid = ktajobid;
            return ((OvertimeRequestService)(this)).findByJobIdAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OvertimeRequestServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OvertimeRequestServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress(StaticClass.Configuration["ServiceURL:ERBOvertimeService"]);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OvertimeRequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.OvertimeRequestServiceImplPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OvertimeRequestServiceClient.GetEndpointAddress(EndpointConfiguration.OvertimeRequestServiceImplPort);
        }

        public enum EndpointConfiguration
        {

            OvertimeRequestServiceImplPort,
        }
    }
}
