//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTA_UserServices
{
    using EServicesWithAngular.Domain.Common;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentity", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class UserIdentity : object
    {
        
        private string UserIdField;
        
        private short LogOnProtocolField;
        
        private bool UnconditionalLogOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short LogOnProtocol
        {
            get
            {
                return this.LogOnProtocolField;
            }
            set
            {
                this.LogOnProtocolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool UnconditionalLogOn
        {
            get
            {
                return this.UnconditionalLogOnField;
            }
            set
            {
                this.UnconditionalLogOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://www.kofax.com/agility/services/sdk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.Session2))]
    public partial class Session : object
    {
        
        private string SessionIdField;
        
        private string ResourceIdField;
        
        private string DisplayNameField;
        
        private bool IsValidField;
        
        private KTA_UserServices.LogonState LogonStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string ResourceId
        {
            get
            {
                return this.ResourceIdField;
            }
            set
            {
                this.ResourceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public KTA_UserServices.LogonState LogonState
        {
            get
            {
                return this.LogonStateField;
            }
            set
            {
                this.LogonStateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonState", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class LogonState : object
    {
        
        private string FormNameField;
        
        private short LogonStateTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FormName
        {
            get
            {
                return this.FormNameField;
            }
            set
            {
                this.FormNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short LogonStateType
        {
            get
            {
                return this.LogonStateTypeField;
            }
            set
            {
                this.LogonStateTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session2", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class Session2 : KTA_UserServices.Session
    {
        
        private bool ReserveLicenseUsedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ReserveLicenseUsed
        {
            get
            {
                return this.ReserveLicenseUsedField;
            }
            set
            {
                this.ReserveLicenseUsedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
        "ndling")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.UserIdentity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.Session))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.LogonState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.UserIdentityWithPassword))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.UserSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.WidgetInfoCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.WidgetInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.DesktopInfoCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.DesktopInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.DesktopWidgetCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.DesktopWidget))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.MobileDeviceSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.LoggedOnUserCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.LoggedOnUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.ResourceIdentity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.LogOnProtocol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.BaseEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.StringCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.UserIdentity2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.UserEmailIdentity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.Session2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.AuthenticationProviderIdentity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.AuthenticationProvidersForSignIn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.AuthenticationProviderIdentityCollection))]
    public partial class CustomExceptionDetail : object
    {
        
        private object CustomDataField;
        
        private System.ServiceModel.ExceptionDetail ExceptionDetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ServiceModel.ExceptionDetail ExceptionDetail
        {
            get
            {
                return this.ExceptionDetailField;
            }
            set
            {
                this.ExceptionDetailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentityWithPassword", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class UserIdentityWithPassword : object
    {
        
        private string UserIdField;
        
        private string PasswordField;
        
        private short LogOnProtocolField;
        
        private bool UnconditionalLogOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short LogOnProtocol
        {
            get
            {
                return this.LogOnProtocolField;
            }
            set
            {
                this.LogOnProtocolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool UnconditionalLogOn
        {
            get
            {
                return this.UnconditionalLogOnField;
            }
            set
            {
                this.UnconditionalLogOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSettings", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class UserSettings : object
    {
        
        private KTA_UserServices.WidgetInfoCollection CustomWidgetsField;
        
        private KTA_UserServices.DesktopInfoCollection DesktopsField;
        
        private KTA_UserServices.WidgetInfoCollection GlobalWidgetsField;
        
        private KTA_UserServices.MobileDeviceSettings MobileDeviceSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.WidgetInfoCollection CustomWidgets
        {
            get
            {
                return this.CustomWidgetsField;
            }
            set
            {
                this.CustomWidgetsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.DesktopInfoCollection Desktops
        {
            get
            {
                return this.DesktopsField;
            }
            set
            {
                this.DesktopsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.WidgetInfoCollection GlobalWidgets
        {
            get
            {
                return this.GlobalWidgetsField;
            }
            set
            {
                this.GlobalWidgetsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.MobileDeviceSettings MobileDeviceSettings
        {
            get
            {
                return this.MobileDeviceSettingsField;
            }
            set
            {
                this.MobileDeviceSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WidgetInfoCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="WidgetInfo")]
    public class WidgetInfoCollection : System.Collections.Generic.List<KTA_UserServices.WidgetInfo>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WidgetInfo", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class WidgetInfo : object
    {
        
        private string AssemblyNameField;
        
        private System.Uri AssemblyUrlField;
        
        private string ConfigurationXmlField;
        
        private string DescriptionField;
        
        private string IconXmlField;
        
        private string IdField;
        
        private string NameField;
        
        private string ParentTypeIdField;
        
        private string TypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName
        {
            get
            {
                return this.AssemblyNameField;
            }
            set
            {
                this.AssemblyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri AssemblyUrl
        {
            get
            {
                return this.AssemblyUrlField;
            }
            set
            {
                this.AssemblyUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfigurationXml
        {
            get
            {
                return this.ConfigurationXmlField;
            }
            set
            {
                this.ConfigurationXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconXml
        {
            get
            {
                return this.IconXmlField;
            }
            set
            {
                this.IconXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentTypeId
        {
            get
            {
                return this.ParentTypeIdField;
            }
            set
            {
                this.ParentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DesktopInfoCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="DesktopInfo")]
    public class DesktopInfoCollection : System.Collections.Generic.List<KTA_UserServices.DesktopInfo>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DesktopInfo", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class DesktopInfo : object
    {
        
        private string DescriptionField;
        
        private KTA_UserServices.DesktopWidgetCollection DesktopWidgetsField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.DesktopWidgetCollection DesktopWidgets
        {
            get
            {
                return this.DesktopWidgetsField;
            }
            set
            {
                this.DesktopWidgetsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DesktopWidgetCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="DesktopWidget")]
    public class DesktopWidgetCollection : System.Collections.Generic.List<KTA_UserServices.DesktopWidget>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DesktopWidget", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class DesktopWidget : object
    {
        
        private double HeightField;
        
        private bool NeedsSavedField;
        
        private int OrderField;
        
        private KTA_UserServices.WidgetInfo WidgetField;
        
        private double WidthField;
        
        private double XPositionField;
        
        private double YPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NeedsSaved
        {
            get
            {
                return this.NeedsSavedField;
            }
            set
            {
                this.NeedsSavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KTA_UserServices.WidgetInfo Widget
        {
            get
            {
                return this.WidgetField;
            }
            set
            {
                this.WidgetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double XPosition
        {
            get
            {
                return this.XPositionField;
            }
            set
            {
                this.XPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double YPosition
        {
            get
            {
                return this.YPositionField;
            }
            set
            {
                this.YPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileDeviceSettings", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class MobileDeviceSettings : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoggedOnUserCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="LoggedOnUser")]
    public class LoggedOnUserCollection : System.Collections.Generic.List<KTA_UserServices.LoggedOnUser>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoggedOnUser", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class LoggedOnUser : object
    {
        
        private KTA_UserServices.ResourceIdentity ResourceField;
        
        private string UserIdField;
        
        private string SessionIdField;
        
        private KTA_UserServices.LogOnProtocol LogOnProtocolField;
        
        private System.Nullable<System.DateTime> LastActiveTimeField;
        
        private System.Nullable<System.DateTime> LastAccessTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public KTA_UserServices.ResourceIdentity Resource
        {
            get
            {
                return this.ResourceField;
            }
            set
            {
                this.ResourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public KTA_UserServices.LogOnProtocol LogOnProtocol
        {
            get
            {
                return this.LogOnProtocolField;
            }
            set
            {
                this.LogOnProtocolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> LastActiveTime
        {
            get
            {
                return this.LastActiveTimeField;
            }
            set
            {
                this.LastActiveTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> LastAccessTime
        {
            get
            {
                return this.LastAccessTimeField;
            }
            set
            {
                this.LastAccessTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceIdentity", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class ResourceIdentity : object
    {
        
        private string IdField;
        
        private string NameField;
        
        private short ResourceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ResourceType
        {
            get
            {
                return this.ResourceTypeField;
            }
            set
            {
                this.ResourceTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOnProtocol", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class LogOnProtocol : KTA_UserServices.BaseEnum
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEnum", Namespace="http://www.kofax.com/agility/services/sdk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KTA_UserServices.LogOnProtocol))]
    public partial class BaseEnum : object
    {
        
        private short ValueField;
        
        private string FormattedAsTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FormattedAsText
        {
            get
            {
                return this.FormattedAsTextField;
            }
            set
            {
                this.FormattedAsTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StringCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="string")]
    public class StringCollection : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentity2", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class UserIdentity2 : object
    {
        
        private string UserIdField;
        
        private short LogOnProtocolField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short LogOnProtocol
        {
            get
            {
                return this.LogOnProtocolField;
            }
            set
            {
                this.LogOnProtocolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEmailIdentity", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class UserEmailIdentity : object
    {
        
        private string EmailAddressField;
        
        private short LogOnProtocolField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short LogOnProtocol
        {
            get
            {
                return this.LogOnProtocolField;
            }
            set
            {
                this.LogOnProtocolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationProviderIdentity", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class AuthenticationProviderIdentity : object
    {
        
        private string IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationProvidersForSignIn", Namespace="http://www.kofax.com/agility/services/sdk")]
    public partial class AuthenticationProvidersForSignIn : object
    {
        
        private KTA_UserServices.AuthenticationProviderIdentityCollection AuthenticationProviderIdentityCollectionField;
        
        private string DefaultSignInUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public KTA_UserServices.AuthenticationProviderIdentityCollection AuthenticationProviderIdentityCollection
        {
            get
            {
                return this.AuthenticationProviderIdentityCollectionField;
            }
            set
            {
                this.AuthenticationProviderIdentityCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DefaultSignInUrl
        {
            get
            {
                return this.DefaultSignInUrlField;
            }
            set
            {
                this.DefaultSignInUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuthenticationProviderIdentityCollection", Namespace="http://www.kofax.com/agility/services/sdk", ItemName="AuthenticationProviderIdentity")]
    public class AuthenticationProviderIdentityCollection : System.Collections.Generic.List<KTA_UserServices.AuthenticationProviderIdentity>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kofax.com/agility/services/sdk", ConfigurationName="KTA_UserServices.IUserService")]
    public interface IUserService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOn", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnCustomExceptionDetail" +
            "Fault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnAsync(KTA_UserServices.UserIdentity userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPassword", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPasswordCustomExc" +
            "eptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithPasswordAsync(KTA_UserServices.UserIdentityWithPassword userIdentityWithPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tion", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tionCustomExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithWindowsAuthenticationAsync(short logOnProtocol, bool unconditionalLogOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOff", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOffResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOffCustomExceptionDetai" +
            "lFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task LogOffAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/FederatedLogOff", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/FederatedLogOffResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/FederatedLogOffCustomExcep" +
            "tionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<string> FederatedLogOffAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/ValidateSession", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/ValidateSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/ValidateSessionCustomExcep" +
            "tionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> ValidateSessionAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/UpdateUserSettings", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/UpdateUserSettingsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/UpdateUserSettingsCustomEx" +
            "ceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task UpdateUserSettingsAsync(string sessionId, KTA_UserServices.UserSettings userSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetUserSettings", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetUserSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetUserSettingsCustomExcep" +
            "tionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.UserSettings> GetUserSettingsAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetLoggedOnUsers", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetLoggedOnUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetLoggedOnUsersCustomExce" +
            "ptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.LoggedOnUserCollection> GetLoggedOnUsersAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOffUsers", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOffUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOffUsersCustomException" +
            "DetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task LogOffUsersAsync(string sessionId, KTA_UserServices.StringCollection sessionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSession", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSessionCustomExceptionD" +
            "etailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> GetSessionAsync(KTA_UserServices.UserIdentity2 userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSessionWithPassword", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetSessionWithPasswordResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSessionWithPasswordCust" +
            "omExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> GetSessionWithPasswordAsync(KTA_UserServices.UserIdentityWithPassword userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddress", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddressRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddressCusto" +
            "mExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithEmailAddressAsync(KTA_UserServices.UserEmailIdentity userEmailIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOn2", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOn2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOn2CustomExceptionDetai" +
            "lFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOn2Async(KTA_UserServices.UserIdentity userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPassword2", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPassword2Response" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithPassword2CustomEx" +
            "ceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithPassword2Async(KTA_UserServices.UserIdentityWithPassword userIdentityWithPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tion2", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tion2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithWindowsAuthentica" +
            "tion2CustomExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithWindowsAuthentication2Async(short logOnProtocol, bool unconditionalLogOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddress2", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddress2Resp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/LogOnWithEmailAddress2Cust" +
            "omExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithEmailAddress2Async(KTA_UserServices.UserEmailIdentity userEmailIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetWindowsUser", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetWindowsUserResponse")]
        System.Threading.Tasks.Task<string> GetWindowsUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/ChangePassword", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/ChangePasswordCustomExcept" +
            "ionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.LogonState> ChangePasswordAsync(string sessionId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "SignInUrl", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "SignInUrlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "SignInUrlCustomExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<string> GetFederatedAuthenticationSignInUrlAsync(string callbackUrl, KTA_UserServices.AuthenticationProviderIdentity authenticationProviderIdentity, short callbackProtocol, string origin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "ProvidersForSignIn", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "ProvidersForSignInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetFederatedAuthentication" +
            "ProvidersForSignInCustomExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.AuthenticationProvidersForSignIn> GetFederatedAuthenticationProvidersForSignInAsync(string callbackUrl, short callbackProtocol, string origin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/ForgotPassword", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/ForgotPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/ForgotPasswordCustomExcept" +
            "ionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task ForgotPasswordAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/ChangeForgottenPassword", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/ChangeForgottenPasswordRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/ChangeForgottenPasswordCus" +
            "tomExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task ChangeForgottenPasswordAsync(string sessionId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/SupplyPasscode", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/SupplyPasscodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/SupplyPasscodeCustomExcept" +
            "ionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.LogonState> SupplyPasscodeAsync(string sessionId, string passcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSingleSignOnSession", ReplyAction="http://www.kofax.com/agility/services/sdk/IUserService/GetSingleSignOnSessionResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KTA_UserServices.CustomExceptionDetail), Action="http://www.kofax.com/agility/services/sdk/IUserService/GetSingleSignOnSessionCust" +
            "omExceptionDetailFault", Name="CustomExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/Agility.Server.Integration.Common.ErrorHa" +
            "ndling")]
        System.Threading.Tasks.Task<KTA_UserServices.Session> GetSingleSignOnSessionAsync(string systemSessionId, KTA_UserServices.UserIdentity2 userIdentity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IUserServiceChannel : KTA_UserServices.IUserService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<KTA_UserServices.IUserService>, KTA_UserServices.IUserService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserServiceClient() : 
                base(UserServiceClient.GetDefaultBinding(), UserServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUserService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), UserServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnAsync(KTA_UserServices.UserIdentity userIdentity)
        {
            return base.Channel.LogOnAsync(userIdentity);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithPasswordAsync(KTA_UserServices.UserIdentityWithPassword userIdentityWithPassword)
        {
            return base.Channel.LogOnWithPasswordAsync(userIdentityWithPassword);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithWindowsAuthenticationAsync(short logOnProtocol, bool unconditionalLogOn)
        {
            return base.Channel.LogOnWithWindowsAuthenticationAsync(logOnProtocol, unconditionalLogOn);
        }
        
        public System.Threading.Tasks.Task LogOffAsync(string sessionId)
        {
            return base.Channel.LogOffAsync(sessionId);
        }
        
        public System.Threading.Tasks.Task<string> FederatedLogOffAsync(string sessionId)
        {
            return base.Channel.FederatedLogOffAsync(sessionId);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> ValidateSessionAsync(string sessionId)
        {
            return base.Channel.ValidateSessionAsync(sessionId);
        }
        
        public System.Threading.Tasks.Task UpdateUserSettingsAsync(string sessionId, KTA_UserServices.UserSettings userSettings)
        {
            return base.Channel.UpdateUserSettingsAsync(sessionId, userSettings);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.UserSettings> GetUserSettingsAsync(string sessionId)
        {
            return base.Channel.GetUserSettingsAsync(sessionId);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.LoggedOnUserCollection> GetLoggedOnUsersAsync(string sessionId)
        {
            return base.Channel.GetLoggedOnUsersAsync(sessionId);
        }
        
        public System.Threading.Tasks.Task LogOffUsersAsync(string sessionId, KTA_UserServices.StringCollection sessionIds)
        {
            return base.Channel.LogOffUsersAsync(sessionId, sessionIds);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> GetSessionAsync(KTA_UserServices.UserIdentity2 userIdentity)
        {
            return base.Channel.GetSessionAsync(userIdentity);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> GetSessionWithPasswordAsync(KTA_UserServices.UserIdentityWithPassword userIdentity)
        {
            return base.Channel.GetSessionWithPasswordAsync(userIdentity);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> LogOnWithEmailAddressAsync(KTA_UserServices.UserEmailIdentity userEmailIdentity)
        {
            return base.Channel.LogOnWithEmailAddressAsync(userEmailIdentity);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOn2Async(KTA_UserServices.UserIdentity userIdentity)
        {
            return base.Channel.LogOn2Async(userIdentity);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithPassword2Async(KTA_UserServices.UserIdentityWithPassword userIdentityWithPassword)
        {
            return base.Channel.LogOnWithPassword2Async(userIdentityWithPassword);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithWindowsAuthentication2Async(short logOnProtocol, bool unconditionalLogOn)
        {
            return base.Channel.LogOnWithWindowsAuthentication2Async(logOnProtocol, unconditionalLogOn);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session2> LogOnWithEmailAddress2Async(KTA_UserServices.UserEmailIdentity userEmailIdentity)
        {
            return base.Channel.LogOnWithEmailAddress2Async(userEmailIdentity);
        }
        
        public System.Threading.Tasks.Task<string> GetWindowsUserAsync()
        {
            return base.Channel.GetWindowsUserAsync();
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.LogonState> ChangePasswordAsync(string sessionId, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(sessionId, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetFederatedAuthenticationSignInUrlAsync(string callbackUrl, KTA_UserServices.AuthenticationProviderIdentity authenticationProviderIdentity, short callbackProtocol, string origin)
        {
            return base.Channel.GetFederatedAuthenticationSignInUrlAsync(callbackUrl, authenticationProviderIdentity, callbackProtocol, origin);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.AuthenticationProvidersForSignIn> GetFederatedAuthenticationProvidersForSignInAsync(string callbackUrl, short callbackProtocol, string origin)
        {
            return base.Channel.GetFederatedAuthenticationProvidersForSignInAsync(callbackUrl, callbackProtocol, origin);
        }
        
        public System.Threading.Tasks.Task ForgotPasswordAsync(string emailAddress)
        {
            return base.Channel.ForgotPasswordAsync(emailAddress);
        }
        
        public System.Threading.Tasks.Task ChangeForgottenPasswordAsync(string sessionId, string newPassword)
        {
            return base.Channel.ChangeForgottenPasswordAsync(sessionId, newPassword);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.LogonState> SupplyPasscodeAsync(string sessionId, string passcode)
        {
            return base.Channel.SupplyPasscodeAsync(sessionId, passcode);
        }
        
        public System.Threading.Tasks.Task<KTA_UserServices.Session> GetSingleSignOnSessionAsync(string systemSessionId, KTA_UserServices.UserIdentity2 userIdentity)
        {
            return base.Channel.GetSingleSignOnSessionAsync(systemSessionId, userIdentity);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserService))
            {
                return new System.ServiceModel.EndpointAddress(StaticClass.Configuration["ServiceURL:KTAUserService"]);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUserService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserService,
        }
    }
}
