//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using CommonLibrary.Configuaration;
using EServicesCommon.DI;

namespace ERP_RefListService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.dirac.com/", ConfigurationName="ERP_RefListService.RefListService")]
    public interface RefListService
    {
        
        // CODEGEN: Parameter 'workflowhistory' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="workflowhistory")]
        ERP_RefListService.GetWorkflowHistoryResponse GetWorkflowHistory(ERP_RefListService.GetWorkflowHistory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.GetWorkflowHistoryResponse> GetWorkflowHistoryAsync(ERP_RefListService.GetWorkflowHistory request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ERP_RefListService.getContractTypesResponse getContractTypes(ERP_RefListService.getContractTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.getContractTypesResponse> getContractTypesAsync(ERP_RefListService.getContractTypes request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ERP_RefListService.getPriorityRulesResponse getPriorityRules(ERP_RefListService.getPriorityRules request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.getPriorityRulesResponse> getPriorityRulesAsync(ERP_RefListService.getPriorityRules request);
        
        // CODEGEN: Parameter 'reflist' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reflist")]
        ERP_RefListService.courseTypesResponse courseTypes(ERP_RefListService.courseTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.courseTypesResponse> courseTypesAsync(ERP_RefListService.courseTypes request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ERP_RefListService.getTenderingTypesResponse getTenderingTypes(ERP_RefListService.getTenderingTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.getTenderingTypesResponse> getTenderingTypesAsync(ERP_RefListService.getTenderingTypes request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ERP_RefListService.getAllDepartmentsResponse getAllDepartments(ERP_RefListService.getAllDepartments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.getAllDepartmentsResponse> getAllDepartmentsAsync(ERP_RefListService.getAllDepartments request);
        
        // CODEGEN: Parameter 'isCommitmentExists' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isCommitmentExists")]
        ERP_RefListService.IsCommitmentExistsResponse IsCommitmentExists(ERP_RefListService.IsCommitmentExists request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.IsCommitmentExistsResponse> IsCommitmentExistsAsync(ERP_RefListService.IsCommitmentExists request);
        
        // CODEGEN: Parameter 'tafqith' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tafqith")]
        ERP_RefListService.GetTafqithResponse GetTafqith(ERP_RefListService.GetTafqith request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.GetTafqithResponse> GetTafqithAsync(ERP_RefListService.GetTafqith request);
        
        // CODEGEN: Parameter 'employeeemail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ERP_RefListService.insertktalogResponse insertktalog(ERP_RefListService.insertktalog request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.insertktalogResponse> insertktalogAsync(ERP_RefListService.insertktalog request);
        
        // CODEGEN: Parameter 'hijradate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="hijradate")]
        ERP_RefListService.gethijradate_arResponse gethijradate_ar(ERP_RefListService.gethijradate_ar request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.gethijradate_arResponse> gethijradate_arAsync(ERP_RefListService.gethijradate_ar request);
        
        // CODEGEN: Parameter 'gregdate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="gregdate")]
        ERP_RefListService.GetGregDateResponse GetGregDate(ERP_RefListService.GetGregDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.GetGregDateResponse> GetGregDateAsync(ERP_RefListService.GetGregDate request);
        
        // CODEGEN: Parameter 'reflist' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reflist")]
        ERP_RefListService.airClassesResponse airClasses(ERP_RefListService.airClasses request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.airClassesResponse> airClassesAsync(ERP_RefListService.airClasses request);
        
        // CODEGEN: Parameter 'hijradate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="hijradate")]
        ERP_RefListService.gethijradateResponse gethijradate(ERP_RefListService.gethijradate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.gethijradateResponse> gethijradateAsync(ERP_RefListService.gethijradate request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        ERP_RefListService.commaFormatedNumberResponse commaFormatedNumber(ERP_RefListService.commaFormatedNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.commaFormatedNumberResponse> commaFormatedNumberAsync(ERP_RefListService.commaFormatedNumber request);
        
        // CODEGEN: Parameter 'reflist' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reflist")]
        ERP_RefListService.flightTypesResponse flightTypes(ERP_RefListService.flightTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_RefListService.flightTypesResponse> flightTypesAsync(ERP_RefListService.flightTypes request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class workflowEntery
    {
        
        private long ad_changelog_idField;
        
        private string roleField;
        
        private string nameField;
        
        private string commentsField;
        
        private long recordidField;
        
        private string notesField;
        
        private string requestDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ad_changelog_id
        {
            get
            {
                return this.ad_changelog_idField;
            }
            set
            {
                this.ad_changelog_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long recordid
        {
            get
            {
                return this.recordidField;
            }
            set
            {
                this.recordidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RequestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class listItem
    {
        
        private long idField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class refList
    {
        
        private long idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkflowHistory", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetWorkflowHistory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ref_id;
        
        public GetWorkflowHistory()
        {
        }
        
        public GetWorkflowHistory(string ref_id)
        {
            this.ref_id = ref_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkflowHistoryResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetWorkflowHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("workflowhistory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.workflowEntery[] workflowhistory;
        
        public GetWorkflowHistoryResponse()
        {
        }
        
        public GetWorkflowHistoryResponse(ERP_RefListService.workflowEntery[] workflowhistory)
        {
            this.workflowhistory = workflowhistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContractTypes", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getContractTypes
    {
        
        public getContractTypes()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContractTypesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getContractTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] result;
        
        public getContractTypesResponse()
        {
        }
        
        public getContractTypesResponse(ERP_RefListService.refList[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPriorityRules", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getPriorityRules
    {
        
        public getPriorityRules()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPriorityRulesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getPriorityRulesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] result;
        
        public getPriorityRulesResponse()
        {
        }
        
        public getPriorityRulesResponse(ERP_RefListService.refList[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="courseTypes", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class courseTypes
    {
        
        public courseTypes()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="courseTypesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class courseTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("reflist", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] reflist;
        
        public courseTypesResponse()
        {
        }
        
        public courseTypesResponse(ERP_RefListService.refList[] reflist)
        {
            this.reflist = reflist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTenderingTypes", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getTenderingTypes
    {
        
        public getTenderingTypes()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTenderingTypesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getTenderingTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] result;
        
        public getTenderingTypesResponse()
        {
        }
        
        public getTenderingTypesResponse(ERP_RefListService.refList[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDepartments", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getAllDepartments
    {
        
        public getAllDepartments()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDepartmentsResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class getAllDepartmentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.listItem[] result;
        
        public getAllDepartmentsResponse()
        {
        }
        
        public getAllDepartmentsResponse(ERP_RefListService.listItem[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsCommitmentExists", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class IsCommitmentExists
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentno;
        
        public IsCommitmentExists()
        {
        }
        
        public IsCommitmentExists(string documentno)
        {
            this.documentno = documentno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsCommitmentExistsResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class IsCommitmentExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isCommitmentExists;
        
        public IsCommitmentExistsResponse()
        {
        }
        
        public IsCommitmentExistsResponse(string isCommitmentExists)
        {
            this.isCommitmentExists = isCommitmentExists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTafqith", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetTafqith
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount;
        
        public GetTafqith()
        {
        }
        
        public GetTafqith(double amount)
        {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTafqithResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetTafqithResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tafqith;
        
        public GetTafqithResponse()
        {
        }
        
        public GetTafqithResponse(string tafqith)
        {
            this.tafqith = tafqith;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertktalog", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class insertktalog
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string employeeemail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ktajoibid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long refid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string role;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string decision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        public insertktalog()
        {
        }
        
        public insertktalog(string employeeemail, string ktajoibid, long refid, string documentno, string role, string decision, string logdate, string description)
        {
            this.employeeemail = employeeemail;
            this.ktajoibid = ktajoibid;
            this.refid = refid;
            this.documentno = documentno;
            this.role = role;
            this.decision = decision;
            this.logdate = logdate;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertktalogResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class insertktalogResponse
    {
        
        public insertktalogResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gethijradate_ar", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class gethijradate_ar
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date;
        
        public gethijradate_ar()
        {
        }
        
        public gethijradate_ar(string date)
        {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gethijradate_arResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class gethijradate_arResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hijradate;
        
        public gethijradate_arResponse()
        {
        }
        
        public gethijradate_arResponse(string hijradate)
        {
            this.hijradate = hijradate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGregDate", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetGregDate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date;
        
        public GetGregDate()
        {
        }
        
        public GetGregDate(string date)
        {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGregDateResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class GetGregDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gregdate;
        
        public GetGregDateResponse()
        {
        }
        
        public GetGregDateResponse(string gregdate)
        {
            this.gregdate = gregdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airClasses", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class airClasses
    {
        
        public airClasses()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airClassesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class airClassesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("reflist", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] reflist;
        
        public airClassesResponse()
        {
        }
        
        public airClassesResponse(ERP_RefListService.refList[] reflist)
        {
            this.reflist = reflist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gethijradate", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class gethijradate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date;
        
        public gethijradate()
        {
        }
        
        public gethijradate(string date)
        {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gethijradateResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class gethijradateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hijradate;
        
        public gethijradateResponse()
        {
        }
        
        public gethijradateResponse(string hijradate)
        {
            this.hijradate = hijradate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="commaFormatedNumber", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class commaFormatedNumber
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal number;
        
        public commaFormatedNumber()
        {
        }
        
        public commaFormatedNumber(decimal number)
        {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="commaFormatedNumberResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class commaFormatedNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result;
        
        public commaFormatedNumberResponse()
        {
        }
        
        public commaFormatedNumberResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="flightTypes", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class flightTypes
    {
        
        public flightTypes()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="flightTypesResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class flightTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("reflist", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERP_RefListService.refList[] reflist;
        
        public flightTypesResponse()
        {
        }
        
        public flightTypesResponse(ERP_RefListService.refList[] reflist)
        {
            this.reflist = reflist;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface RefListServiceChannel : ERP_RefListService.RefListService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class RefListServiceClient : System.ServiceModel.ClientBase<ERP_RefListService.RefListService>, ERP_RefListService.RefListService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RefListServiceClient() : 
                base(RefListServiceClient.GetDefaultBinding(), RefListServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RefListServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefListServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RefListServiceClient.GetBindingForEndpoint(endpointConfiguration), RefListServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefListServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RefListServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefListServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RefListServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RefListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.GetWorkflowHistoryResponse ERP_RefListService.RefListService.GetWorkflowHistory(ERP_RefListService.GetWorkflowHistory request)
        {
            return base.Channel.GetWorkflowHistory(request);
        }
        
        public ERP_RefListService.workflowEntery[] GetWorkflowHistory(string ref_id)
        {
            ERP_RefListService.GetWorkflowHistory inValue = new ERP_RefListService.GetWorkflowHistory();
            inValue.ref_id = ref_id;
            ERP_RefListService.GetWorkflowHistoryResponse retVal = ((ERP_RefListService.RefListService)(this)).GetWorkflowHistory(inValue);
            return retVal.workflowhistory;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.GetWorkflowHistoryResponse> ERP_RefListService.RefListService.GetWorkflowHistoryAsync(ERP_RefListService.GetWorkflowHistory request)
        {
            return base.Channel.GetWorkflowHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.GetWorkflowHistoryResponse> GetWorkflowHistoryAsync(string ref_id)
        {
            ERP_RefListService.GetWorkflowHistory inValue = new ERP_RefListService.GetWorkflowHistory();
            inValue.ref_id = ref_id;
            return ((ERP_RefListService.RefListService)(this)).GetWorkflowHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.getContractTypesResponse ERP_RefListService.RefListService.getContractTypes(ERP_RefListService.getContractTypes request)
        {
            return base.Channel.getContractTypes(request);
        }
        
        public ERP_RefListService.refList[] getContractTypes()
        {
            ERP_RefListService.getContractTypes inValue = new ERP_RefListService.getContractTypes();
            ERP_RefListService.getContractTypesResponse retVal = ((ERP_RefListService.RefListService)(this)).getContractTypes(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.getContractTypesResponse> ERP_RefListService.RefListService.getContractTypesAsync(ERP_RefListService.getContractTypes request)
        {
            return base.Channel.getContractTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.getContractTypesResponse> getContractTypesAsync()
        {
            ERP_RefListService.getContractTypes inValue = new ERP_RefListService.getContractTypes();
            return ((ERP_RefListService.RefListService)(this)).getContractTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.getPriorityRulesResponse ERP_RefListService.RefListService.getPriorityRules(ERP_RefListService.getPriorityRules request)
        {
            return base.Channel.getPriorityRules(request);
        }
        
        public ERP_RefListService.refList[] getPriorityRules()
        {
            ERP_RefListService.getPriorityRules inValue = new ERP_RefListService.getPriorityRules();
            ERP_RefListService.getPriorityRulesResponse retVal = ((ERP_RefListService.RefListService)(this)).getPriorityRules(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.getPriorityRulesResponse> ERP_RefListService.RefListService.getPriorityRulesAsync(ERP_RefListService.getPriorityRules request)
        {
            return base.Channel.getPriorityRulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.getPriorityRulesResponse> getPriorityRulesAsync()
        {
            ERP_RefListService.getPriorityRules inValue = new ERP_RefListService.getPriorityRules();
            return ((ERP_RefListService.RefListService)(this)).getPriorityRulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.courseTypesResponse ERP_RefListService.RefListService.courseTypes(ERP_RefListService.courseTypes request)
        {
            return base.Channel.courseTypes(request);
        }
        
        public ERP_RefListService.refList[] courseTypes()
        {
            ERP_RefListService.courseTypes inValue = new ERP_RefListService.courseTypes();
            ERP_RefListService.courseTypesResponse retVal = ((ERP_RefListService.RefListService)(this)).courseTypes(inValue);
            return retVal.reflist;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.courseTypesResponse> ERP_RefListService.RefListService.courseTypesAsync(ERP_RefListService.courseTypes request)
        {
            return base.Channel.courseTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.courseTypesResponse> courseTypesAsync()
        {
            ERP_RefListService.courseTypes inValue = new ERP_RefListService.courseTypes();
            return ((ERP_RefListService.RefListService)(this)).courseTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.getTenderingTypesResponse ERP_RefListService.RefListService.getTenderingTypes(ERP_RefListService.getTenderingTypes request)
        {
            return base.Channel.getTenderingTypes(request);
        }
        
        public ERP_RefListService.refList[] getTenderingTypes()
        {
            ERP_RefListService.getTenderingTypes inValue = new ERP_RefListService.getTenderingTypes();
            ERP_RefListService.getTenderingTypesResponse retVal = ((ERP_RefListService.RefListService)(this)).getTenderingTypes(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.getTenderingTypesResponse> ERP_RefListService.RefListService.getTenderingTypesAsync(ERP_RefListService.getTenderingTypes request)
        {
            return base.Channel.getTenderingTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.getTenderingTypesResponse> getTenderingTypesAsync()
        {
            ERP_RefListService.getTenderingTypes inValue = new ERP_RefListService.getTenderingTypes();
            return ((ERP_RefListService.RefListService)(this)).getTenderingTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.getAllDepartmentsResponse ERP_RefListService.RefListService.getAllDepartments(ERP_RefListService.getAllDepartments request)
        {
            return base.Channel.getAllDepartments(request);
        }
        
        public ERP_RefListService.listItem[] getAllDepartments()
        {
            ERP_RefListService.getAllDepartments inValue = new ERP_RefListService.getAllDepartments();
            ERP_RefListService.getAllDepartmentsResponse retVal = ((ERP_RefListService.RefListService)(this)).getAllDepartments(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.getAllDepartmentsResponse> ERP_RefListService.RefListService.getAllDepartmentsAsync(ERP_RefListService.getAllDepartments request)
        {
            return base.Channel.getAllDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.getAllDepartmentsResponse> getAllDepartmentsAsync()
        {
            ERP_RefListService.getAllDepartments inValue = new ERP_RefListService.getAllDepartments();
            return ((ERP_RefListService.RefListService)(this)).getAllDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.IsCommitmentExistsResponse ERP_RefListService.RefListService.IsCommitmentExists(ERP_RefListService.IsCommitmentExists request)
        {
            return base.Channel.IsCommitmentExists(request);
        }
        
        public string IsCommitmentExists(string documentno)
        {
            ERP_RefListService.IsCommitmentExists inValue = new ERP_RefListService.IsCommitmentExists();
            inValue.documentno = documentno;
            ERP_RefListService.IsCommitmentExistsResponse retVal = ((ERP_RefListService.RefListService)(this)).IsCommitmentExists(inValue);
            return retVal.isCommitmentExists;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.IsCommitmentExistsResponse> ERP_RefListService.RefListService.IsCommitmentExistsAsync(ERP_RefListService.IsCommitmentExists request)
        {
            return base.Channel.IsCommitmentExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.IsCommitmentExistsResponse> IsCommitmentExistsAsync(string documentno)
        {
            ERP_RefListService.IsCommitmentExists inValue = new ERP_RefListService.IsCommitmentExists();
            inValue.documentno = documentno;
            return ((ERP_RefListService.RefListService)(this)).IsCommitmentExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.GetTafqithResponse ERP_RefListService.RefListService.GetTafqith(ERP_RefListService.GetTafqith request)
        {
            return base.Channel.GetTafqith(request);
        }
        
        public string GetTafqith(double amount)
        {
            ERP_RefListService.GetTafqith inValue = new ERP_RefListService.GetTafqith();
            inValue.amount = amount;
            ERP_RefListService.GetTafqithResponse retVal = ((ERP_RefListService.RefListService)(this)).GetTafqith(inValue);
            return retVal.tafqith;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.GetTafqithResponse> ERP_RefListService.RefListService.GetTafqithAsync(ERP_RefListService.GetTafqith request)
        {
            return base.Channel.GetTafqithAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.GetTafqithResponse> GetTafqithAsync(double amount)
        {
            ERP_RefListService.GetTafqith inValue = new ERP_RefListService.GetTafqith();
            inValue.amount = amount;
            return ((ERP_RefListService.RefListService)(this)).GetTafqithAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.insertktalogResponse ERP_RefListService.RefListService.insertktalog(ERP_RefListService.insertktalog request)
        {
            return base.Channel.insertktalog(request);
        }
        
        public void insertktalog(string employeeemail, string ktajoibid, long refid, string documentno, string role, string decision, string logdate, string description)
        {
            ERP_RefListService.insertktalog inValue = new ERP_RefListService.insertktalog();
            inValue.employeeemail = employeeemail;
            inValue.ktajoibid = ktajoibid;
            inValue.refid = refid;
            inValue.documentno = documentno;
            inValue.role = role;
            inValue.decision = decision;
            inValue.logdate = logdate;
            inValue.description = description;
            ERP_RefListService.insertktalogResponse retVal = ((ERP_RefListService.RefListService)(this)).insertktalog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.insertktalogResponse> ERP_RefListService.RefListService.insertktalogAsync(ERP_RefListService.insertktalog request)
        {
            return base.Channel.insertktalogAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.insertktalogResponse> insertktalogAsync(string employeeemail, string ktajoibid, long refid, string documentno, string role, string decision, string logdate, string description)
        {
            ERP_RefListService.insertktalog inValue = new ERP_RefListService.insertktalog();
            inValue.employeeemail = employeeemail;
            inValue.ktajoibid = ktajoibid;
            inValue.refid = refid;
            inValue.documentno = documentno;
            inValue.role = role;
            inValue.decision = decision;
            inValue.logdate = logdate;
            inValue.description = description;
            return ((ERP_RefListService.RefListService)(this)).insertktalogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.gethijradate_arResponse ERP_RefListService.RefListService.gethijradate_ar(ERP_RefListService.gethijradate_ar request)
        {
            return base.Channel.gethijradate_ar(request);
        }
        
        public string gethijradate_ar(string date)
        {
            ERP_RefListService.gethijradate_ar inValue = new ERP_RefListService.gethijradate_ar();
            inValue.date = date;
            ERP_RefListService.gethijradate_arResponse retVal = ((ERP_RefListService.RefListService)(this)).gethijradate_ar(inValue);
            return retVal.hijradate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.gethijradate_arResponse> ERP_RefListService.RefListService.gethijradate_arAsync(ERP_RefListService.gethijradate_ar request)
        {
            return base.Channel.gethijradate_arAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.gethijradate_arResponse> gethijradate_arAsync(string date)
        {
            ERP_RefListService.gethijradate_ar inValue = new ERP_RefListService.gethijradate_ar();
            inValue.date = date;
            return ((ERP_RefListService.RefListService)(this)).gethijradate_arAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.GetGregDateResponse ERP_RefListService.RefListService.GetGregDate(ERP_RefListService.GetGregDate request)
        {
            return base.Channel.GetGregDate(request);
        }
        
        public string GetGregDate(string date)
        {
            ERP_RefListService.GetGregDate inValue = new ERP_RefListService.GetGregDate();
            inValue.date = date;
            ERP_RefListService.GetGregDateResponse retVal = ((ERP_RefListService.RefListService)(this)).GetGregDate(inValue);
            return retVal.gregdate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.GetGregDateResponse> ERP_RefListService.RefListService.GetGregDateAsync(ERP_RefListService.GetGregDate request)
        {
            return base.Channel.GetGregDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.GetGregDateResponse> GetGregDateAsync(string date)
        {
            ERP_RefListService.GetGregDate inValue = new ERP_RefListService.GetGregDate();
            inValue.date = date;
            return ((ERP_RefListService.RefListService)(this)).GetGregDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.airClassesResponse ERP_RefListService.RefListService.airClasses(ERP_RefListService.airClasses request)
        {
            return base.Channel.airClasses(request);
        }
        
        public ERP_RefListService.refList[] airClasses()
        {
            ERP_RefListService.airClasses inValue = new ERP_RefListService.airClasses();
            ERP_RefListService.airClassesResponse retVal = ((ERP_RefListService.RefListService)(this)).airClasses(inValue);
            return retVal.reflist;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.airClassesResponse> ERP_RefListService.RefListService.airClassesAsync(ERP_RefListService.airClasses request)
        {
            return base.Channel.airClassesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.airClassesResponse> airClassesAsync()
        {
            ERP_RefListService.airClasses inValue = new ERP_RefListService.airClasses();
            return ((ERP_RefListService.RefListService)(this)).airClassesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.gethijradateResponse ERP_RefListService.RefListService.gethijradate(ERP_RefListService.gethijradate request)
        {
            return base.Channel.gethijradate(request);
        }
        
        public string gethijradate(string date)
        {
            ERP_RefListService.gethijradate inValue = new ERP_RefListService.gethijradate();
            inValue.date = date;
            ERP_RefListService.gethijradateResponse retVal = ((ERP_RefListService.RefListService)(this)).gethijradate(inValue);
            return retVal.hijradate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.gethijradateResponse> ERP_RefListService.RefListService.gethijradateAsync(ERP_RefListService.gethijradate request)
        {
            return base.Channel.gethijradateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.gethijradateResponse> gethijradateAsync(string date)
        {
            ERP_RefListService.gethijradate inValue = new ERP_RefListService.gethijradate();
            inValue.date = date;
            return ((ERP_RefListService.RefListService)(this)).gethijradateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.commaFormatedNumberResponse ERP_RefListService.RefListService.commaFormatedNumber(ERP_RefListService.commaFormatedNumber request)
        {
            return base.Channel.commaFormatedNumber(request);
        }
        
        public string commaFormatedNumber(decimal number)
        {
            ERP_RefListService.commaFormatedNumber inValue = new ERP_RefListService.commaFormatedNumber();
            inValue.number = number;
            ERP_RefListService.commaFormatedNumberResponse retVal = ((ERP_RefListService.RefListService)(this)).commaFormatedNumber(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.commaFormatedNumberResponse> ERP_RefListService.RefListService.commaFormatedNumberAsync(ERP_RefListService.commaFormatedNumber request)
        {
            return base.Channel.commaFormatedNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.commaFormatedNumberResponse> commaFormatedNumberAsync(decimal number)
        {
            ERP_RefListService.commaFormatedNumber inValue = new ERP_RefListService.commaFormatedNumber();
            inValue.number = number;
            return ((ERP_RefListService.RefListService)(this)).commaFormatedNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_RefListService.flightTypesResponse ERP_RefListService.RefListService.flightTypes(ERP_RefListService.flightTypes request)
        {
            return base.Channel.flightTypes(request);
        }
        
        public ERP_RefListService.refList[] flightTypes()
        {
            ERP_RefListService.flightTypes inValue = new ERP_RefListService.flightTypes();
            ERP_RefListService.flightTypesResponse retVal = ((ERP_RefListService.RefListService)(this)).flightTypes(inValue);
            return retVal.reflist;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_RefListService.flightTypesResponse> ERP_RefListService.RefListService.flightTypesAsync(ERP_RefListService.flightTypes request)
        {
            return base.Channel.flightTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_RefListService.flightTypesResponse> flightTypesAsync()
        {
            ERP_RefListService.flightTypes inValue = new ERP_RefListService.flightTypes();
            return ((ERP_RefListService.RefListService)(this)).flightTypesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RefListServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            var _config = FactoryManager.Instance.Resolve<ICoreConfigurations>();
            if ((endpointConfiguration == EndpointConfiguration.RefListServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress(_config.ERBRefListService);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RefListServiceClient.GetBindingForEndpoint(EndpointConfiguration.RefListServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RefListServiceClient.GetEndpointAddress(EndpointConfiguration.RefListServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            RefListServiceImplPort,
        }
    }
}
