//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EServicesWithAngular.Domain.Common;

namespace ERB_IdentificationLetter
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.dirac.com/", ConfigurationName="ERB_IdentificationLetter.LetterRequestService")]
    public interface LetterRequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.verifyBeforeSaveResponse> verifyBeforeSaveAsync(ERB_IdentificationLetter.verifyBeforeSave request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.cancelLetterRequestResponse> cancelLetterRequestAsync(ERB_IdentificationLetter.cancelLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.findoneResponse> findoneAsync(ERB_IdentificationLetter.findone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.saveNewLetterRequestResponse> saveNewLetterRequestAsync(ERB_IdentificationLetter.saveNewLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.updateKtaJobIdResponse> updateKtaJobIdAsync(ERB_IdentificationLetter.updateKtaJobId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.findByJobIdResponse> findByJobIdAsync(ERB_IdentificationLetter.findByJobId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.releaseLetterRequestResponse> releaseLetterRequestAsync(ERB_IdentificationLetter.releaseLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.updateExistingLetterRequestResponse> updateExistingLetterRequestAsync(ERB_IdentificationLetter.updateExistingLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.rejectLetterRequestResponse> rejectLetterRequestAsync(ERB_IdentificationLetter.rejectLetterRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class letterRequest
    {
        
        private long idField;
        
        private int employeeidField;
        
        private lookup employeeField;
        
        private string statuscodeField;
        
        private lookup statusField;
        
        private string documentnoField;
        
        private string ktajobidField;
        
        private int doctypeidField;
        
        private lookup doctypeField;
        
        private string datetrxField;
        
        private int sIGNATURETYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int employeeid
        {
            get
            {
                return this.employeeidField;
            }
            set
            {
                this.employeeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public lookup employee
        {
            get
            {
                return this.employeeField;
            }
            set
            {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statuscode
        {
            get
            {
                return this.statuscodeField;
            }
            set
            {
                this.statuscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public lookup status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string documentno
        {
            get
            {
                return this.documentnoField;
            }
            set
            {
                this.documentnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ktajobid
        {
            get
            {
                return this.ktajobidField;
            }
            set
            {
                this.ktajobidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int doctypeid
        {
            get
            {
                return this.doctypeidField;
            }
            set
            {
                this.doctypeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public lookup doctype
        {
            get
            {
                return this.doctypeField;
            }
            set
            {
                this.doctypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string datetrx
        {
            get
            {
                return this.datetrxField;
            }
            set
            {
                this.datetrxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int SIGNATURETYPE
        {
            get
            {
                return this.sIGNATURETYPEField;
            }
            set
            {
                this.sIGNATURETYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class lookup
    {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dirac.com/")]
    public partial class dsLetterRequestResult
    {
        
        private bool successField;
        
        private string errorMsgCodeField;
        
        private string errorMsgDescriptionField;
        
        private string errorMsgDescriptionarField;
        
        private letterRequest letterrequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMsgCode
        {
            get
            {
                return this.errorMsgCodeField;
            }
            set
            {
                this.errorMsgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMsgDescription
        {
            get
            {
                return this.errorMsgDescriptionField;
            }
            set
            {
                this.errorMsgDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorMsgDescriptionar
        {
            get
            {
                return this.errorMsgDescriptionarField;
            }
            set
            {
                this.errorMsgDescriptionarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public letterRequest letterrequest
        {
            get
            {
                return this.letterrequestField;
            }
            set
            {
                this.letterrequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyBeforeSave", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class verifyBeforeSave
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public verifyBeforeSave()
        {
        }
        
        public verifyBeforeSave(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyBeforeSaveResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class verifyBeforeSaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public verifyBeforeSaveResponse()
        {
        }
        
        public verifyBeforeSaveResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelLetterRequest", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class cancelLetterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public cancelLetterRequest()
        {
        }
        
        public cancelLetterRequest(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelLetterRequestResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class cancelLetterRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public cancelLetterRequestResponse()
        {
        }
        
        public cancelLetterRequestResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findone", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class findone
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        public findone()
        {
        }
        
        public findone(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findoneResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class findoneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public findoneResponse()
        {
        }
        
        public findoneResponse(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveNewLetterRequest", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class saveNewLetterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public saveNewLetterRequest()
        {
        }
        
        public saveNewLetterRequest(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveNewLetterRequestResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class saveNewLetterRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public saveNewLetterRequestResponse()
        {
        }
        
        public saveNewLetterRequestResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateKtaJobId", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class updateKtaJobId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long reqID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ktajobid;
        
        public updateKtaJobId()
        {
        }
        
        public updateKtaJobId(long reqID, string ktajobid)
        {
            this.reqID = reqID;
            this.ktajobid = ktajobid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateKtaJobIdResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class updateKtaJobIdResponse
    {
        
        public updateKtaJobIdResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByJobId", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class findByJobId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ktajobid;
        
        public findByJobId()
        {
        }
        
        public findByJobId(string ktajobid)
        {
            this.ktajobid = ktajobid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByJobIdResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class findByJobIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public findByJobIdResponse()
        {
        }
        
        public findByJobIdResponse(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="releaseLetterRequest", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class releaseLetterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public releaseLetterRequest()
        {
        }
        
        public releaseLetterRequest(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="releaseLetterRequestResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class releaseLetterRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public releaseLetterRequestResponse()
        {
        }
        
        public releaseLetterRequestResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateExistingLetterRequest", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class updateExistingLetterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public updateExistingLetterRequest()
        {
        }
        
        public updateExistingLetterRequest(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateExistingLetterRequestResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class updateExistingLetterRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public updateExistingLetterRequestResponse()
        {
        }
        
        public updateExistingLetterRequestResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rejectLetterRequest", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class rejectLetterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.letterRequest letterrequest;
        
        public rejectLetterRequest()
        {
        }
        
        public rejectLetterRequest(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            this.letterrequest = letterrequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rejectLetterRequestResponse", WrapperNamespace="http://service.dirac.com/", IsWrapped=true)]
    public partial class rejectLetterRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dirac.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ERB_IdentificationLetter.dsLetterRequestResult result;
        
        public rejectLetterRequestResponse()
        {
        }
        
        public rejectLetterRequestResponse(ERB_IdentificationLetter.dsLetterRequestResult result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface LetterRequestServiceChannel : ERB_IdentificationLetter.LetterRequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class LetterRequestServiceClient : System.ServiceModel.ClientBase<ERB_IdentificationLetter.LetterRequestService>, ERB_IdentificationLetter.LetterRequestService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LetterRequestServiceClient() : 
                base(LetterRequestServiceClient.GetDefaultBinding(), LetterRequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LetterRequestServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LetterRequestServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LetterRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), LetterRequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LetterRequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LetterRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LetterRequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LetterRequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LetterRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.verifyBeforeSaveResponse> ERB_IdentificationLetter.LetterRequestService.verifyBeforeSaveAsync(ERB_IdentificationLetter.verifyBeforeSave request)
        {
            return base.Channel.verifyBeforeSaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.verifyBeforeSaveResponse> verifyBeforeSaveAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.verifyBeforeSave inValue = new ERB_IdentificationLetter.verifyBeforeSave();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).verifyBeforeSaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.cancelLetterRequestResponse> ERB_IdentificationLetter.LetterRequestService.cancelLetterRequestAsync(ERB_IdentificationLetter.cancelLetterRequest request)
        {
            return base.Channel.cancelLetterRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.cancelLetterRequestResponse> cancelLetterRequestAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.cancelLetterRequest inValue = new ERB_IdentificationLetter.cancelLetterRequest();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).cancelLetterRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.findoneResponse> ERB_IdentificationLetter.LetterRequestService.findoneAsync(ERB_IdentificationLetter.findone request)
        {
            return base.Channel.findoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.findoneResponse> findoneAsync(long id)
        {
            ERB_IdentificationLetter.findone inValue = new ERB_IdentificationLetter.findone();
            inValue.id = id;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).findoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.saveNewLetterRequestResponse> ERB_IdentificationLetter.LetterRequestService.saveNewLetterRequestAsync(ERB_IdentificationLetter.saveNewLetterRequest request)
        {
            return base.Channel.saveNewLetterRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.saveNewLetterRequestResponse> saveNewLetterRequestAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.saveNewLetterRequest inValue = new ERB_IdentificationLetter.saveNewLetterRequest();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).saveNewLetterRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.updateKtaJobIdResponse> ERB_IdentificationLetter.LetterRequestService.updateKtaJobIdAsync(ERB_IdentificationLetter.updateKtaJobId request)
        {
            return base.Channel.updateKtaJobIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.updateKtaJobIdResponse> updateKtaJobIdAsync(long reqID, string ktajobid)
        {
            ERB_IdentificationLetter.updateKtaJobId inValue = new ERB_IdentificationLetter.updateKtaJobId();
            inValue.reqID = reqID;
            inValue.ktajobid = ktajobid;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).updateKtaJobIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.findByJobIdResponse> ERB_IdentificationLetter.LetterRequestService.findByJobIdAsync(ERB_IdentificationLetter.findByJobId request)
        {
            return base.Channel.findByJobIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.findByJobIdResponse> findByJobIdAsync(string ktajobid)
        {
            ERB_IdentificationLetter.findByJobId inValue = new ERB_IdentificationLetter.findByJobId();
            inValue.ktajobid = ktajobid;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).findByJobIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.releaseLetterRequestResponse> ERB_IdentificationLetter.LetterRequestService.releaseLetterRequestAsync(ERB_IdentificationLetter.releaseLetterRequest request)
        {
            return base.Channel.releaseLetterRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.releaseLetterRequestResponse> releaseLetterRequestAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.releaseLetterRequest inValue = new ERB_IdentificationLetter.releaseLetterRequest();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).releaseLetterRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.updateExistingLetterRequestResponse> ERB_IdentificationLetter.LetterRequestService.updateExistingLetterRequestAsync(ERB_IdentificationLetter.updateExistingLetterRequest request)
        {
            return base.Channel.updateExistingLetterRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.updateExistingLetterRequestResponse> updateExistingLetterRequestAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.updateExistingLetterRequest inValue = new ERB_IdentificationLetter.updateExistingLetterRequest();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).updateExistingLetterRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERB_IdentificationLetter.rejectLetterRequestResponse> ERB_IdentificationLetter.LetterRequestService.rejectLetterRequestAsync(ERB_IdentificationLetter.rejectLetterRequest request)
        {
            return base.Channel.rejectLetterRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERB_IdentificationLetter.rejectLetterRequestResponse> rejectLetterRequestAsync(ERB_IdentificationLetter.letterRequest letterrequest)
        {
            ERB_IdentificationLetter.rejectLetterRequest inValue = new ERB_IdentificationLetter.rejectLetterRequest();
            inValue.letterrequest = letterrequest;
            return ((ERB_IdentificationLetter.LetterRequestService)(this)).rejectLetterRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LetterRequestServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LetterRequestServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress(StaticClass.Configuration["ServiceURL:ERBIdentificationLetter"]);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LetterRequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.LetterRequestServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LetterRequestServiceClient.GetEndpointAddress(EndpointConfiguration.LetterRequestServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            LetterRequestServiceImplPort,
        }
    }
}
